config/routes.rb
Rails.application.routes.draw do

root to: 'sessions#new'
resource :professor, only: [:new, :create, :edit, :update, :show] do
  resources :preferences
  get '/lectures' => 'professors#lectures'
  get '/lectures_graph' => 'professors#lectures_graph'
end

resource :session, only: [:new, :create, :destroy]

namespace :admin do
  get '/offerings/score' => 'offerings#score'
  post '/offerings/random' => 'offerings#random'
  get '/offerings/domagic' => 'offerings#domagic'
  get '/offerings/domagicalltheway' => 'offerings#domagicalltheway'
  get '/offerings/clear' => 'offerings#clear_assignment'
  resources :professors do
    get '/preferences' => 'professors#preferences'
    get '/lectures' => 'professors#lectures'
  end
  resources :offerings do
    put '/resetprof' => 'offerings#resetprof'
  end
  resources :courses do
    get '/preferences' => 'courses#preferences'
    get '/lectures' => 'courses#lectures'
  end
  resource :preferences, only: [:index] do
    get '/professors' => 'preferences#professors'
    get '/offerings' => 'preferences#offerings'
  end
  get '/' => 'dashboard#index'
  post '/semester' => 'dashboard#semester'
  post '/notify_all' => 'dashboard#notify_all'

end

resources :lectures

end

app/models/offering.rb
class Offering < ActiveRecord::Base
  belongs_to :course
  belongs_to :professor

  # validate :restrict_schedule_format


  def self.decode_schedule(code)
    result = []
    code.split("").each do |value|
      case value
      when "a"
        result.push("Monday")
      when "b"
        result.push("Tuesday")
      when "c"
        result.push("Wednesday")
      when "d"
        result.push("Thursday")
      when "e"
        result.push("Friday")
      when "1"
        result.push("8-10")
      when "2"
        result.push("10-12")
      when "3"
        result.push("12-14")
      when "4"
        result.push("14-16")
      when "5"
        result.push("16-18")
      when "6"
        result.push("18-20")
      when "7"
        result.push("19-21")
      when "8"
        result.push("21-23")
      end     
    end
    result.join(" ") 
  end

  # def restrict_schedule_format
  #   arr1 = []
  #   i = 0
  #   (self.schedule.length / 2).times do
  #     arr1 << self.schedule.slice(i,2)
  #     i += 2
  #   end
  #   unless self.schedule.length > 0 && /^([a-z]\d)*/.match(self.schedule)[0].length == self.schedule.length && arr1.length == arr1.uniq.length
  #     errors.add(:schedule, 'is not valid.') 
  #   end
  # end

end

app/controllers/admin/offerings_controller.rb
class Admin::OfferingsController < ApplicationController

  before_filter :restrict_access
  before_filter :restrict_admin_access
  before_action :set_offering, only: [:show, :edit, :update, :destroy]


  def index
    Copypref.populate_to_copyprefs
    @results = Magic.get_preference_bycourse_copy(Offering.where(semester: current_semester))
    @preferences = Preference.where(semester: current_semester)
    ##stuff in here are hidden unless being clicked
    @offerings = Offering.where(semester: current_semester)
    @offering = Offering.new
    #################
  end

  def new
    @offering = Offering.new
  end

  def create
    @offering = Offering.new(offering_params)
    @offering.semester = current_semester
    if @offering.save
      redirect_to admin_offerings_path
    else
      @offerings = Offering.where(semester: current_semester)
      @results = Magic.get_preference_bycourse_copy(Offering.where(semester: current_semester))
      @preferences = Preference.where(semester: current_semester)
      render :index
    end
  end

  def destroy
    @offering.destroy
    redirect_to admin_offerings_path
  end

  def edit
  end
  
  def update
    if @offering.update_attributes(offering_params)
      redirect_to admin_offerings_path
    else
      render :edit
    end
  end

  def clear_assignment
    Offering.where(semester: current_semester).each do |object|
      object.professor_id = nil
      object.save
    end
    Copypref.populate_to_copyprefs
    redirect_to admin_offerings_path
  end

  def resetprof
    @offering = Offering.find(params[:offering_id])
    @offering.professor_id = nil
    if @offering.save
      flash[:alert] = "Successfully reset the professor."
      redirect_to admin_offerings_path
    else
      flash[:alert] = "Failed due to some unexpected error."
      redirect_to admin_offerings_path
    end
  end

  def domagic
    Magic.do_magic
    redirect_to admin_offerings_path
  end

  def domagicalltheway
    Magic.do_magic_all_the_way
    redirect_to admin_offerings_path
  end

  def score
    begin 
      score = Magic.calculate_score(10,8,5)
    rescue
      score = ""
    end
    render plain: score
  end

  def random
    Magic.go_random(params[:number_of_random].to_i)
    redirect_to admin_offerings_path
  end

private
  # Use callbacks to share common setup or constraints between actions.
  def set_offering
    @offering = Offering.find(params[:id])
  end

  def offering_params
    params.require(:offering).permit(:course_id, :letter, :schedule, :professor_id)
  end

end

app/helpers/admin/offerings_helper.rb
module Admin::OfferingsHelper
  
end

app/views/admin/offerings/create.html.erb
<h1>Admin::Offerings#create</h1>
<p>Find me in app/views/admin/offerings/create.html.erb</p>

app/views/admin/offerings/destroy.html.erb
<h1>Admin::Offerings#destroy</h1>
<p>Find me in app/views/admin/offerings/destroy.html.erb</p>

app/views/admin/offerings/edit.html.erb
<div class='well col-md-offset-2' style='width: 50%'>
  <h3>Edit <%=@offering.course.name%> <%=@offering.letter%></h3>
  <h3>Currently:</h3>
  <h4><%=Offering.decode_schedule(@offering.schedule)%></h4>
  <%= form_for [:admin, @offering] do |f| %>
    <%i=0%>
    <div class='form-group'>
      <div id="timeforms">
      <% schedule = Offering.decode_schedule(@offering.schedule).split(' ') %>
      <% coded_schedule = @offering.schedule.split('') %>
        <%(@offering.course.credits / 2).times do%>
          <div class='col-md-2' style="margin-top: 1%">Day</div>
          <div class='col-md-10'>
            <select class='form-control' id=<%="day#{i}"%> >
              <option value='<%= coded_schedule.shift %>' ><%=schedule.shift%></option>
              <option value='a'>Monday</option><option value='b'>Tuesday</option><option value='c'>Wednesday</option><option value='d'>Thursday</option><option value='e'>Friday</option>
            </select>
          </div>
          <div class='col-md-2' style="margin-top: 1%">Time</div>
          <div class='col-md-10'>
            <select class='form-control' id=<%="time#{i}"%>>
            <option value='<%= coded_schedule.shift %>' ><%=schedule.shift%></option>
              <option value='1'>8-10</option><option value='2'>10-12</option><option value='3'>12-14</option><option value='4'>14-16</option><option value='5'>16-18</option><option value='6'>18-20</option><option value='7'>19-21</option><option value='8'>21-23</option>
            </select>
          </div>
          <%i+=1%>
        <%end%>
      </div>
    </div>
    <div class="form-group" style="display: none">
      <%= f.label :schedule %><br>
      <%= f.text_field :schedule %>
    </div>
    <div class="form-group">
      <div class='col-md-2' style="margin-top: 1%"><%= f.label :professor_id%></div>
      <div class='col-md-10'>
      <%= f.select :professor_id, options_for_select(Professor.pluck(:name, :id).push(["To be assigned",nil])), {prompt: "Please select"}, { class: 'form-control'}%>
      </div>
    </div>
    
    <div class="actions form-group">
      <%= f.submit 'submit',class: 'btn btn-primary' %>
    </div>
  <% end %>
  <%= link_to 'Destroy', admin_offering_path(@offering), {method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-danger' ,stysle: "color:blue"} %>
</div>

app/views/admin/offerings/index.html.erb
<% if @offering.errors.any? %>
  <div class="alert alert-danger">
    <div>
      <%= pluralize(@offering.errors.count, "error") %> prevented this offering from being submitted:
        <ul>
          <% @offering.errors.full_messages.each do |msg|%>
          <li> <%= msg %></li>
          <% end %>
        </ul>
    </div>
  </div>
<% end %>


<div class="loading" style="display:none" >
  <div class="ball"></div>
  Assigning professors
</div>
        
<div id='needtohide' style="display:initial">
  <h5>Current Semester: <%= decode_semester(current_semester) %></h5>
  <table class='table table-hover'  id='admin_offering_table'>
    <caption><h4>Offerings Listing</h4></caption>
    <thead>
      <tr>
        <th>Name</th>
        <th>Letter</th>
        <th>Schedule</th>
        <th>Professor</th>
        <th>
          <div class='row'>
            <div class='bg-success' style='float: left;margin-right:2px'>Assigned Twice</div>
            <div class='bg-info'>Assigned Once</div>
          </div>
        </th>
      </tr>
    </thead>

    <tbody>
      <% @offerings.to_a.sort_by!{|element| element.course.name}.each do |offering| %>
        <% if offering.professor && offering.professor.offerings.where(semester: current_semester).count == 2 %>
          <tr class='bg-success'>
        <% elsif offering.professor && offering.professor.offerings.where(semester: current_semester).count == 1 %>
          <tr class='bg-info'>
        <% else %>
          <tr>
        <% end %>
          <td><%= link_to offering.course.name,edit_admin_offering_path(offering) %></td>
          <td id='offering_table_letter'><%= offering.letter %></td>
          <td><%= Offering.decode_schedule(offering.schedule) %></td>
          <%if offering.professor_id%>
            <td><a data-toggle='modal' data-target='#<%=offering.professor.name.gsub(/\W/,'_')%>'><%= offering.professor.name %></a></td>
          <%else%>
            <td style="color:red;">To be assigned</td>
          <%end%>
          <td>
          <% if offering.professor_id %>
            <%= link_to 'Remove professor',admin_offering_resetprof_path(offering),method: :put %>
          <% end %>
          </td>
          <td>
            <button class='btn btn-default' data-toggle='modal' data-target='#<%=offering.id%>'>View Preferences</button>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>

  <div class="panel-default well">
    <div class="panel-heading">
      <h3 class='panel-title'>Add new offering</h3>
    </div>
    <div class="panel-body">
      <%= form_for [:admin, @offering] do |f| %>
        <div class="form-group col-md-4">
          <%= f.label :course_id %><br>
          <%= f.select :course_id, options_for_select(Course.order(:name).pluck(:name, :id)),{:prompt => "Please select"}, {class:"form-control"} %>
        <div id="timeforms"></div>
        </div>
        <div class="form-group col-md-4">
          <%= f.label :letter %><br>
          <%= f.select :letter,options_for_select(("A".."Z").to_a.zip(("A".."Z").to_a)),{:prompt => "Please select"}, {class: "form-control"} %>
        </div>
        <div class="form-group" style="display: none">
          <%= f.label :schedule %><br>
          <%= f.text_field :schedule %>
        </div>
        <div class="form-group col-md-4">
          <%= f.label :professor_id %><br>
          <%= f.select :professor_id, options_for_select(Professor.pluck(:name, :id)),{:prompt => "Please select"}, {class: "form-control"} %>
        </div>
        <div class="actions col-md-4">
          <button type="submit" class="btn btn-primary">Add Offering</button>
        </div>
      <% end %>
    </div>
  </div>

  <div class='row'>
    <%= link_to 'Notify All Professors (email each professor)', admin_notify_all_path, method: :post, data: {confirm: 'Are you sure?'},class: 'btn btn-warning col-md-4 col-md-offset-1'  %>
    <div class='btn btn-default col-md-1' style='background:cyan;margin-left:2px;width:150px' id='score_button'>Score</div>
  </div>
  <div class='row'>
    <%= link_to 'Remove all professors', admin_offerings_clear_path, class: 'btn btn-danger col-md-4 col-md-offset-1', data: {confirm: 'Are you sure?'} %>
    <%= form_tag admin_offerings_random_path, method: :post do %>
      <%= number_field_tag :number_of_random,nil,{style: 'width:50px;margin:5px 0 0 5px'} %>
      <%= submit_tag 'Random', {class: 'btn btn-default col-md-1',style: 'background:pink;width:75px;margin-left:2px', id: "random_button"} %>
    <% end %>
  </div>
    <%= link_to 'Magic GO Stepwise!', admin_offerings_domagic_path , method: :get,class: 'btn btn-info col-md-2',style: 'padding:25px;margin-left:60%;margin-top:-6%;height:70px;', id: "magicbutton"  %>
    <%= link_to 'Magic All the Way!', admin_offerings_domagicalltheway_path , method: :get,class: 'btn btn-primary col-md-2',style: 'padding:25px;margin-left:80%;margin-top:-6%;height:70px;', id: "magicallbutton"  %>
  <div id='view_score'>
    <div id='score_box'>
    </div>
  </div>

  <!--                                                                -->
  <div class='container'>
    <% major = @results[0] %>
    <% major.each do |hash| %>

    <div class="panel-primary modal fade" id='<%=hash[:offering_id]%>' tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel">
    <div class='modal-dialog' role='document' style="width: 90%">
    <div class='modal-content'>

    <div class="panel-primary well">
      <div class="panel-heading">
        <h3><%= hash[:course]%> <%= hash[:letter]%></h3>
        <h5><%= Offering.decode_schedule(hash[:schedule])%></h5>
      </div>
      <div class='panel-body'>
        <div class='row'>
          <div class='col-md-2 btn btn-info'>First choice</div>
          <div class='col-md-10'>
              <% hash[:first_choice_of].each do |professor_name| %>
                <button class='btn btn-default' data-toggle='modal' data-target='#<%=professor_name.gsub(/\W/,'_')%>'><%= professor_name %></button>
            <% end %> 
          </div>
        </div>
        <div class='row'>
          <div class='col-md-2 btn btn-info'>Second choice</div>
          <div class='col-md-10'>
              <% hash[:second_choice_of].each do |professor_name| %>
                <button class='btn btn-default' data-toggle='modal' data-target='#<%=professor_name.gsub(/\W/,'_')%>'><%= professor_name %></button>
              <% end %>
          </div>
        </div>
        <div class='row'>
          <div class='col-md-2 btn btn-info'>Third choice</div>
          <div class='col-md-10'>
              <% hash[:third_choice_of].each do |professor_name| %>
                <button class='btn btn-default' data-toggle='modal' data-target='#<%=professor_name.gsub(/\W/,'_')%>'><%= professor_name %></button>
              <% end %>
          </div>
        </div>
      </div>
    </div>
    </div>
    </div>
    </div>
  <% end %>


      <% servicecourse = (@results[1])%>
      <% servicecourse.each do |service_course|%>

      <div class="panel-primary modal fade" id='<%=service_course[:offering_id]%>' tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel">
      <div class='modal-dialog' role='document' style="width: 90%">
      <div class='modal-content'>

      <div class="panel-primary well">
        <div class="panel-heading">
          <h3><%= service_course[:course]%> <%= service_course[:letter]%></h3>
          <h5><%=Offering.decode_schedule(service_course[:schedule])%></h5>
        </div>
        <div class='panel-body'>
          <div class='row'>
            <div class='col-md-2 btn btn-info'>First choice</div>
            <div class='col-md-10'>
                <% service_course[:first_choice_of].each do |professor_name| %>
                  <button class='btn btn-default' data-toggle='modal' data-target='#<%=professor_name.gsub(/\W/,'_')%>'><%= professor_name %></button>
              <% end %> 
            </div>
          </div>
          <div class='row'>
            <div class='col-md-2 btn btn-info'>Second choice</div>
            <div class='col-md-10'>
                <% service_course[:second_choice_of].each do |professor_name| %>
                  <button class='btn btn-default' data-toggle='modal' data-target='#<%=professor_name.gsub(/\W/,'_')%>'><%= professor_name %></button>
                <% end %>
            </div>
          </div>
          <div class='row'>
            <div class='col-md-2 btn btn-info'>Third choice</div>
            <div class='col-md-10'>
                <% service_course[:third_choice_of].each do |professor_name| %>
                  <button class='btn btn-default' data-toggle='modal' data-target='#<%=professor_name.gsub(/\W/,'_')%>'><%= professor_name %></button>
                <% end %>
            </div>
          </div>
        </div>
      </div>
      </div>
      </div>
      </div>
    <% end %>
  </div>




    <% @preferences.each do |preference| %>
      <div class="panel-primary modal fade" id='<%=preference.professor.name.gsub(/\W/,'_')%>' tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel">
        <div class='modal-dialog' role='document' style="width: 90%">
        <div class='modal-content'>
        <div class="panel-heading" id='exampleModalLabel'>
          <h3 class='panel-title'>
            <%= preference.professor.name%></h3><h4><%=decode_semester(preference.semester)%></h4>
        </div>
        <div class='panel-body'>
          <h5 class='col-md-4'>First preference for major:</h5><h5 class='col-md-3'><strong><%= Offering.find(preference.first_major).course.name%></strong></h5><h5 class='col-md-5'><%= Offering.decode_schedule(Offering.find(preference.first_major).schedule)%></h5>
          <h5 class='col-md-4'>Second preference for major:</h5><h5 class='col-md-3'><strong><%=Offering.find(preference.second_major).course.name%></strong></h5><h5 class='col-md-5'><%= Offering.decode_schedule(Offering.find(preference.second_major).schedule)%></h5>
          <h5 class='col-md-4'>Third preference for major:</h5><h5 class='col-md-3'><strong><%=Offering.find(preference.third_major).course.name%></strong></h5><h5 class='col-md-5'><%= Offering.decode_schedule(Offering.find(preference.third_major).schedule)%></h5>
          <h5 class='col-md-4'>First preference for service:</h5><h5 class='col-md-3'><strong><%= Offering.find(preference.first_service).course.name%></strong></h5><h5 class='col-md-5'><%= Offering.decode_schedule(Offering.find(preference.first_service).schedule)%></h5>
          <h5 class='col-md-4'>Second preference for service:</h5><h5 class='col-md-3'><strong><%=Offering.find(preference.second_service).course.name%></strong></h5><h5 class='col-md-5'><%= Offering.decode_schedule(Offering.find(preference.second_service).schedule)%></h5>
          <h5 class='col-md-4'>Third preference for service:</h5><h5 class='col-md-3'><strong><%=Offering.find(preference.third_service).course.name%></strong></h5><h5 class='col-md-5'><%= Offering.decode_schedule(Offering.find(preference.third_service).schedule)%></h5>
        </div>
      </div>
      </div>
      </div>
    <%end%>
</div>

app/views/admin/offerings/new.html.erb
<%= form_for [:admin, @offering] do |f| %>
  <div class="field">
    <%= f.label :course_id %><br>
    <%= f.select :course_id, options_for_select(Course.pluck(:name, :id)) %>
  </div>
  <div class="field">
    <%= f.label :letter %><br>
    <%= f.text_field :letter %>
  </div>
  <div class="field">
    <%= f.label :schedule %><br>
    <%= f.text_field :schedule %>
  </div>
  <div class="field">
    <%= f.label :professor_id %><br>
    <%= f.text_field :professor_id %>
  </div>
  
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/admin/offerings/show.html.erb
<h1>Admin::Offerings#show</h1>
<p>Find me in app/views/admin/offerings/show.html.erb</p>

app/views/admin/offerings/update.html.erb
<h1>Admin::Offerings#update</h1>
<p>Find me in app/views/admin/offerings/update.html.erb</p>