config/routes.rb
Rails.application.routes.draw do

root to: 'sessions#new'
resource :professor, only: [:new, :create, :edit, :update, :show] do
  resources :preferences
  get '/lectures' => 'professors#lectures'
  get '/lectures_graph' => 'professors#lectures_graph'
end

resource :session, only: [:new, :create, :destroy]

namespace :admin do
  get '/offerings/score' => 'offerings#score'
  post '/offerings/random' => 'offerings#random'
  get '/offerings/domagic' => 'offerings#domagic'
  get '/offerings/domagicalltheway' => 'offerings#domagicalltheway'
  get '/offerings/clear' => 'offerings#clear_assignment'
  resources :professors do
    get '/preferences' => 'professors#preferences'
    get '/lectures' => 'professors#lectures'
  end
  resources :offerings do
    put '/resetprof' => 'offerings#resetprof'
  end
  resources :courses do
    get '/preferences' => 'courses#preferences'
    get '/lectures' => 'courses#lectures'
  end
  resource :preferences, only: [:index] do
    get '/professors' => 'preferences#professors'
    get '/offerings' => 'preferences#offerings'
  end
  get '/' => 'dashboard#index'
  post '/semester' => 'dashboard#semester'
  post '/notify_all' => 'dashboard#notify_all'

end

resources :lectures

end

app/models/preference.rb
class Preference < ActiveRecord::Base
  belongs_to :professor
  # validates :ttc_proposal_1, presence: true
  validate :uniq_preference_major?
  validate :uniq_preference_service?

  def uniq_preference_major?
    if (self.first_major == self.second_major || self.first_major == self.third_major || self.second_major == self.third_major)
      errors.add(:base,"Major preferences must be distinct.")
    end
  end

   def uniq_preference_service?
    if self.first_service == self.second_service || self.first_service == self.third_service || self.second_service == self.third_service
      errors.add(:base,"Service preferences must be distinct.")
    end
  end
end

app/controllers/admin/preferences_controller.rb
class Admin::PreferencesController < ApplicationController
  include Admin::PreferencesHelper
  

  # def index
  #     @preferences = Preference.where(semester: current_semester)
  #     # @professors = Professor.all
  #     @results = get_preference_bycourse(Offering.where(semester: current_semester))
  # end

  def professors
    @preferences = Preference.where(semester: current_semester)
  end


  def offerings
    @results = get_preference_bycourse(Offering.where(semester: current_semester))
    @preferences = Preference.where(semester: current_semester)
  end

end

app/controllers/preferences_controller.rb
  class PreferencesController < ApplicationController
  
  before_filter :restrict_access


  def index
    @preferences = current_professor.preferences
    @addable = addable?(current_professor,current_semester)
  end

  def create
    @professor = current_professor
    @offerings = Offering.where(semester: current_semester)
    @preference = @professor.preferences.build(preference_params)
    @preference.semester = current_semester
    @offering_major_selector = Offering.where(semester: current_semester).joins(:course).order("courses.name ASC").select{|offering|Course.find(offering.course_id).kind =='major'}
    @offering_service_selector = Offering.where(semester: current_semester).joins(:course).order("courses.name ASC").select{|offering|Course.find(offering.course_id).kind == 'service'}
    @offering_major_selector = @offering_major_selector.map do|offering|
          [Course.find(offering.course_id).name + " " + offering.letter, offering.id]
    end
    @offering_service_selector = @offering_service_selector.map do|offering|
          [Course.find(offering.course_id).name + " " + offering.letter, offering.id]
    end
    if @preference.save
      flash[:alert] = "Your preferences had been added!"
      Copypref.populate_to_copyprefs
      redirect_to professor_preferences_path
    else
      render :new
    end
  end

  def show
    #is this doing anything?
    @results = get_preference_bycourse(Offering.all)
  end

  def new
    if addable?(current_professor,current_semester)
      @offerings = Offering.where(semester: current_semester)
      @preference = Preference.new

      #this only select offerings of Major
      @offering_major_selector = Offering.where(semester: current_semester).joins(:course).order("courses.name ASC").select{|offering|Course.find(offering.course_id).kind =='major'}
      #this only select offerings of Service
      @offering_service_selector = Offering.where(semester: current_semester).joins(:course).order("courses.name ASC").select{|offering|Course.find(offering.course_id).kind == 'service'}
      #Create the major selector array for dropdown form
      @offering_major_selector = @offering_major_selector.map do|offering|
          [Course.find(offering.course_id).name + " " + offering.letter, offering.id]
      end
      #Create the service selector array for dropdown form
      @offering_service_selector = @offering_service_selector.map do|offering|
          [Course.find(offering.course_id).name + " " + offering.letter, offering.id]
      end
    else
      redirect_to professor_preferences_path
    end
  end

  def edit
    @preference = Preference.find(params[:id])
    @offerings = Offering.where(semester: @preference.semester)
    @offering_major_selector = Offering.where(semester: @preference.semester).joins(:course).order("courses.name ASC").select{|offering|Course.find(offering.course_id).kind =='major'}
    @offering_service_selector = Offering.where(semester: @preference.semester).joins(:course).order("courses.name ASC").select{|offering|Course.find(offering.course_id).kind == 'service'}
    @offering_major_selector = @offering_major_selector.map do|offering|
      [Course.find(offering.course_id).name + " " + offering.letter, offering.id]
    end
    @offering_service_selector = @offering_service_selector.map do|offering|
      [Course.find(offering.course_id).name + " " + offering.letter, offering.id]
    end
  end

  def update
    @preference = current_professor.preferences.find(params[:id])
    @offerings = Offering.where(semester: @preference.semester)

    @offering_major_selector = Offering.where(semester: @preference.semester).joins(:course).order("courses.name ASC").select{|offering|Course.find(offering.course_id).kind =='major'}
    @offering_service_selector = Offering.where(semester: @preference.semester).joins(:course).order("courses.name ASC").select{|offering|Course.find(offering.course_id).kind == 'service'}
    @offering_major_selector = @offering_major_selector.map do|offering|
      [Course.find(offering.course_id).name + " " + offering.letter, offering.id]
    end
    @offering_service_selector = @offering_service_selector.map do|offering|
      [Course.find(offering.course_id).name + " " + offering.letter, offering.id]
    end

    if @preference.update(preference_params)
      redirect_to professor_preferences_path
      Copypref.populate_to_copyprefs
      flash[:alert] = "Your preferences had been updated!"
    else
      render 'edit'
    end
  end

  def destroy
    @preference = Preference.find(params[:id])
    @preference.destroy
    redirect_to professor_preferences_path
  end

  protected
  def preference_params
    params.require(:preference).permit(:first_major, :second_major, :third_major, :first_service, :second_service, :third_service, :ttc_proposal_1, :ttc_proposal_2,:ttc_proposal_3, :comments, :semester)
  end

  def addable?(current_professor,current_semester)
    !current_professor.preferences.where(semester: current_semester).pluck(:professor_id).include?(current_professor.id)
  end

end

app/helpers/admin/preferences_helper.rb
module Admin::PreferencesHelper

#based on offering_id returns a hash with all information about that offering
  # def get_info(offering_id)
  #   offering = Offering.find(offering_id)
  #   name = offering.course.name
  #   if offering.course.kind == "major"
  #     pref1 = Preference.where(first_major: offering_id)
  #     prof_first_choice = []
  #     pref1.each do |preference|
  #       prof_first_choice.push(preference.professor.name)
  #     end
  #     prof_second_choice = []
  #     pref2 = Preference.where(second_major: offering_id)
  #     pref2.each do |preference|
  #       prof_second_choice.push(preference.professor.name)
  #     end
  #     prof_third_choice = []
  #     pref3 = Preference.where(third_major: offering_id)
  #     pref3.each do |preference|
  #       prof_third_choice.push(preference.professor.name)
  #     end      
  #   else
  #     pref1 = Preference.where(first_service: offering_id)
  #     prof_first_choice = []
  #     pref1.each do |preference|
  #       prof_first_choice.push(preference.professor.name)
  #     end
  #     prof_second_choice = []
  #     pref2 = Preference.where(second_service: offering_id)
  #     pref2.each do |preference|
  #       prof_second_choice.push(preference.professor.name)
  #     end
  #     prof_third_choice = []
  #     pref3 = Preference.where(third_service: offering_id)


  #     pref3.each do |preference|
  #       prof_third_choice.push(preference.professor.name)
  #     end       
  #   end      
  #   result = {}
  #   result[:course] = name
  #   result[:letter] = offering.letter
  #   result[:schedule] = offering.schedule
  #   result[:semester] = offering.semester
  #   result[:first_choice_of] = prof_first_choice
  #   result[:second_choice_of] = prof_second_choice
  #   result[:third_choice_of] = prof_third_choice
  #   result[:offering_id] = offering_id
  #   result
  # end

  # #Creates arrays one for major and one for service of hashes with information about preferences
  # def get_preference_bycourse(offerings)
  #   major_offering_ids = []
  #   service_offering_ids =[]
  #   offerings.each do |offering|
  #     if offering.course.kind == "major"
  #       major_offering_ids.push(offering.id)
  #     else
  #       service_offering_ids.push(offering.id)
  #     end
  #   end
  #   organized_major_pref = []
  #   major_offering_ids.each do |offering|
  #     organized_major_pref.push(get_info(offering))
  #   end
  #   organized_service_pref = []
  #   service_offering_ids.each do |offering|
  #     organized_service_pref.push(get_info(offering))
  #   end
  #   organized = [organized_major_pref,organized_service_pref]
  #   organized
  # end

  # #gets the history of preferences for every courses by every offering of that course
  # def course_preferences_reporter
  #   result = []
  #   Course.all.each do |course|
  #     course.offerings.each do |offering|
  #       report = {}
  #       report[:course_name] = offering.course.name
  #       report[:letter] = offering.letter
  #       report[:schedule] = offering.schedule
  #       report[:semester] = offering.semester
  #       if course.kind == "major"
  #         report[:first_choice_of] = Preference.where(first_major: offering.id).pluck(:professor_id)
  #         report[:second_choice_of] = Preference.where(second_major: offering.id).pluck(:professor_id)
  #         report[:third_choice_of] = Preference.where(third_major: offering.id).pluck(:professor_id)
  #       else
  #         report[:first_choice_of] = Preference.where(first_service: offering.id).pluck(:professor_id)
  #         report[:second_choice_of] = Preference.where(second_service: offering.id).pluck(:professor_id)
  #         report[:third_choice_of] = Preference.where(third_service: offering.id).pluck(:professor_id)
  #       end
  #       result << report
  #     end
  #   end
  #   result
  # end

  # #filters results returned by previous methods by a single course name
  # def display_report(results,course)
  #   results.select {|hash| hash[:course_name] == course}
  # end

  # def decode_semester(date_format)
  #   result = nil
  #   case date_format.month
  #   when 1
  #     result = 0
  #   when 3
  #     result = 1
  #   when 8
  #     result = 2    
  #   end
  #   "#{result}/#{date_format.year}"
  # end


  # def group_service_preferences_by_schedule(results)
  #   uniq_schedules = Course.joins("LEFT OUTER JOIN offerings ON courses.id=offerings.course_id").pluck(:schedule).uniq    
  #   service_ids = Course.where(kind: "service").pluck(:id)
  #   result = []
  #   uniq_schedules.each do |schedule|
  #     service_ids.each do |service_id|
  #       hash = {}
  #       hash[:first_choice_of] = []
  #       hash[:second_choice_of] = []
  #       hash[:third_choice_of] = []
  #       group = results.select {|singular| singular[:course] == Course.find(service_id).name && singular[:schedule] == schedule }
  #         group.each do |preference|
  #           hash[:first_choice_of].concat(preference[:first_choice_of])
  #           hash[:second_choice_of].concat(preference[:second_choice_of])
  #           hash[:third_choice_of].concat(preference[:third_choice_of])
  #           hash[:course] = preference[:course]
  #           hash[:schedule] = preference[:schedule]            
  #         end
  #       result << hash
  #     end
  #   end
  # result
  # result = result.select {|x| x.has_key?(:course)}
  # result
  # end

end

app/views/preferences/edit.html.erb
<% if @preference.errors.any? %>
  <div class="alert alert-danger">
    <div>
      <%= pluralize(@preference.errors.count, "error") %> prevented this preference from being submitted:
        <ul>
          <% @preference.errors.full_messages.each do |msg|%>
          <li> <%= msg %></li>
          <% end %>
        </ul>
    </div>
  </div>
<% end %>

<h1 style="display: inline">Offering List
</h1>
<h2 style="display: inline; color: blue">Editing Semester: <%= @preference.semester%></h2>


<table class="table table-condensed" id='edit_professor_offering_table'>
  <thead>
    <tr>
      <th>Name</th>
      <th>letter</th>
      <th>schedule</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @offerings.each do |offering| %>
      <tr>
        <td><%= offering.course.name %></td>
        <td><%= offering.letter %></td>
        <td><%= Offering.decode_schedule(offering.schedule) %></td>
      </tr>
    <% end %>
  </tbody>
</table>


<div class="panel-default well">
  <div class="panel-heading">
    <h2 class='panel-title'>Please update your preferences: </h2>
</div>
  <div class="panel-body">
    <%= form_for [:professor, @preference], url: {action: "update"}, :html => {class: 'form-horizontal'} do |f| %>
      <div class='row'>
        <div class='col-md-6'>
          <div class='form-group'>
            <div class="col-md-4">
              <%= f.label 'First Major'%>
            </div>
            <div class="col-md-8">   
              <%= f.select :first_major, options_for_select(@offering_major_selector),{},class: 'form-control' %>
            </div>
          </div>
          <div class='form-group'>
            <div class="col-md-4">
              <%= f.label 'Second Major'%>
            </div>
            <div class="col-md-8">   
              <%= f.select :second_major, options_for_select(@offering_major_selector),{},class: 'form-control' %>
            </div>
          </div>
          <div class='form-group'>
            <div class="col-md-4">
              <%= f.label 'Third Major'%>
            </div>
            <div class="col-md-8">   
              <%= f.select :third_major, options_for_select(@offering_major_selector),{},class: 'form-control' %>
            </div>
          </div>
        </div>
        <div class='col-md-6'>
          <div class='form-group'>
            <div class="col-md-4">
              <%= f.label 'First Service'%>
            </div>
            <div class="col-md-8">   
              <%= f.select :first_service, options_for_select(@offering_service_selector),{},class: 'form-control' %>
            </div>
          </div>
          <div class='form-group'>
            <div class="col-md-4">
              <%= f.label 'Second Service'%>
            </div>
            <div class="col-md-8">   
              <%= f.select :second_service, options_for_select(@offering_service_selector),{},class: 'form-control' %>
            </div>
          </div>
          <div class='form-group'>
            <div class="col-md-4">
              <%= f.label 'Third Service'%>
            </div>
            <div class="col-md-8">   
              <%= f.select :third_service, options_for_select(@offering_service_selector),{},class: 'form-control' %>
            </div>
          </div>
        </div>
      </div>
      <div class='row'>
        <div class='col-md-6'>
          <div class='form-group'>
            <%= f.label 'Proposal Project 1',class: 'col-sm-4'  %>
            <%= f.text_field :ttc_proposal_1%>
          </div>
          <div class='form-group'>
            <%= f.label 'Proposal Project 2',class: 'col-sm-4'  %>
            <%= f.text_field :ttc_proposal_2 %>
          </div>
          <div class='form-group'>
            <%= f.label 'Proposal Project 3',class: 'col-sm-4'  %>
            <%= f.text_field :ttc_proposal_3 %>
          </div>
        </div>
        <div class='col-md-6'>
          <div class='form-group'>
            <%= f.label 'Comment',class: 'col-sm-3' %>
            <%= f.text_area :comments, class: 'col-sm-9', id: 'preferenceComment' %>
          </div>
        </div>
      </div>
        <%= f.submit 'Update', :class => 'col-md-2 btn btn-primary' %>
    <% end %> 
  </div>
</div>

app/views/preferences/index.html.erb
<h2>List of Preferences</h2>

<table class="table table-hover">
  <thead>
    <tr>
      <th>First Major</th>
      <th>Second Major</th>
      <th>Third Major</th>
      <th>First Service</th>
      <th>Second Service</th>
      <th>Third Service</th>
      <th>First Project</th>
      <th>Second Project</th>
      <th>Third Project</th>
      <th>Semester</th>
      <th colspan="3"></th>
    </tr>
  </thead>
  <tbody>
    <% @preferences.each do |preference| %>
    <tr>
        <td><%= Course.find(Offering.find(preference.first_major).course_id).name%> <em><%=Offering.find(preference.first_major).letter%></em></td>
        <td><%= Course.find(Offering.find(preference.second_major).course_id).name %> <em><%=Offering.find(preference.second_major).letter%></em></td>
        <td><%= Course.find(Offering.find(preference.third_major).course_id).name %> <em><%=Offering.find(preference.third_major).letter%></em></td>
        <td><%= Course.find(Offering.find(preference.first_service).course_id).name %> <em><%=Offering.find(preference.first_service).letter%></em></td>
        <td><%= Course.find(Offering.find(preference.second_service).course_id).name %> <em><%=Offering.find(preference.second_service).letter%></em></td>
        <td><%= Course.find(Offering.find(preference.third_service).course_id).name %> <em><%=Offering.find(preference.third_service).letter%></em></td>
        <td><%= preference.ttc_proposal_1 %></td>
        <td><%= preference.ttc_proposal_2 %></td>
        <td><%= preference.ttc_proposal_3 %></td>
        <td><%= decode_semester(preference.semester) %></td>
        <%if preference.semester == current_semester%>
          <td><%= link_to 'Edit', edit_professor_preference_path(preference) %></td>
          <td><%= link_to 'Destroy', professor_preference_path(preference), method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <%end%>
      </tr>
    <% end %>
  </tbody>
</table>
<div class="bg-success" id="onePreference"><h4><strong>You can only submit <u>ONE</u> preference each semester.</strong></h4></div>
<% if @addable %>
  <%= link_to 'New Preference', new_professor_preference_path,class: 'btn btn-primary' %>
<% end %>

app/views/preferences/new.html.erb
<% if @preference.errors.any? %>
  <div class="alert alert-danger">
    <div>
      <%= pluralize(@preference.errors.count, "error") %> prevented this preference from being submitted:
        <ul>
          <% @preference.errors.full_messages.each do |msg|%>
          <li> <%= msg %></li>
          <% end %>
        </ul>
    </div>
  </div>
<% end %>

<h1 style="display: inline">Offering List
</h1>
<h2 style="display: inline">current semester: <%= current_semester%></h2>

<table class="table table-condensed" id='professor_offering_table'>
  <thead>
    <tr>
      <th>Name</th>
      <th>letter</th>
      <th>schedule</th>
      <th colspan="3"></th>
    </tr>
  </thead>
<% if !@offerings.empty? %>
  <tbody>
    <% @offerings.each do |offering| %>
      <tr>
        <td><%= offering.course.name %></td>
        <td><%= offering.letter %></td>
        <td><%= Offering.decode_schedule(offering.schedule) %></td>
      </tr>
    <% end %>
  </tbody>
<% end %>
</table>


<div class="panel-default well">
  <div class="panel-heading">
    <h2 class='panel-title'>Based on the above offering list, please choose your preferences: </h2>
</div>
  <div class="panel-body">
    <%= form_for [:professor, @preference], url: {action: "create"}, :html => {class: 'form-horizontal'} do |f| %>
      <div class='row'>
        <div class='col-md-6'>
          <div class='form-group'>
            <div class="col-md-4">
              <%= f.label 'First Major',style:'padding: 2px'%>
            </div>
            <div class="col-md-8">   
              <%= f.select :first_major, options_for_select(@offering_major_selector),{},class: 'form-control' %>
            </div>
          </div>
          <div class='form-group'>
            <div class="col-md-4">
              <%= f.label 'Second Major',style:'padding: 2px'%>
            </div>
            <div class="col-md-8">   
              <%= f.select :second_major, options_for_select(@offering_major_selector),{},class: 'form-control' %>
            </div>
          </div>
          <div class='form-group'>
            <div class="col-md-4">
              <%= f.label 'Third Major',style:'padding: 2px'%>
            </div>
            <div class="col-md-8">   
              <%= f.select :third_major, options_for_select(@offering_major_selector),{},class: 'form-control' %>
            </div>
          </div>
        </div>
        <div class='col-md-6'>
          <div class='form-group'>
            <div class="col-md-4">
              <%= f.label 'First Service',style:'padding: 2px'%>
            </div>
            <div class="col-md-8">   
              <%= f.select :first_service, options_for_select(@offering_service_selector),{},class: 'form-control' %>
            </div>
          </div>
          <div class='form-group'>
            <div class="col-md-4">
              <%= f.label 'Second Service',style:'padding: 2px'%>
            </div>
            <div class="col-md-8">   
              <%= f.select :second_service, options_for_select(@offering_service_selector),{},class: 'form-control' %>
            </div>
          </div>
          <div class='form-group'>
            <div class="col-md-4">
              <%= f.label 'Third Service',style:'padding: 2px'%>
            </div>
            <div class="col-md-8">   
              <%= f.select :third_service, options_for_select(@offering_service_selector),{},class: 'form-control' %>
            </div>
          </div>
        </div>
      </div>
      <div class='row'>
        <div class='col-md-6'>
          <div class='form-group'>
            <%= f.label 'Proposal Project 1',class: 'col-sm-4'  %>
            <%= f.text_field :ttc_proposal_1%>
          </div>
          <div class='form-group'>
            <%= f.label 'Proposal Project 2',class: 'col-sm-4'  %>
            <%= f.text_field :ttc_proposal_2 %>
          </div>
          <div class='form-group'>
            <%= f.label 'Proposal Project 3',class: 'col-sm-4'  %>
            <%= f.text_field :ttc_proposal_3 %>
          </div>
        </div>
        <div class='col-md-6'>
          <div class='form-group'>
            <%= f.label 'Comment',class: 'col-sm-3' %>
            <%= f.text_area :comments, class: 'col-sm-9', id: 'preferenceComment' %>
          </div>
        </div>
      </div>
        <%= f.submit 'Create', :class => 'col-md-2 btn btn-primary' %>
    <% end %> 
  </div>
</div>