config/routes.rb
Rails.application.routes.draw do

root to: 'sessions#new'
resource :professor, only: [:new, :create, :edit, :update, :show] do
  resources :preferences
  get '/lectures' => 'professors#lectures'
  get '/lectures_graph' => 'professors#lectures_graph'
end

resource :session, only: [:new, :create, :destroy]

namespace :admin do
  get '/offerings/score' => 'offerings#score'
  post '/offerings/random' => 'offerings#random'
  get '/offerings/domagic' => 'offerings#domagic'
  get '/offerings/domagicalltheway' => 'offerings#domagicalltheway'
  get '/offerings/clear' => 'offerings#clear_assignment'
  resources :professors do
    get '/preferences' => 'professors#preferences'
    get '/lectures' => 'professors#lectures'
  end
  resources :offerings do
    put '/resetprof' => 'offerings#resetprof'
  end
  resources :courses do
    get '/preferences' => 'courses#preferences'
    get '/lectures' => 'courses#lectures'
  end
  resource :preferences, only: [:index] do
    get '/professors' => 'preferences#professors'
    get '/offerings' => 'preferences#offerings'
  end
  get '/' => 'dashboard#index'
  post '/semester' => 'dashboard#semester'
  post '/notify_all' => 'dashboard#notify_all'

end

resources :lectures

end

app/models/professor.rb
class Professor < ActiveRecord::Base
  has_secure_password
  has_many :preferences
  has_many :lectures
  has_many :offerings
  has_many :copyprefs

end

app/controllers/admin/professors_controller.rb
class Admin::ProfessorsController < ApplicationController

  before_filter :restrict_access
  before_filter :restrict_admin_access

  def index
    @professors = Professor.all
    @new_professor = Professor.new
  end


  def create
    @professor = Professor.new(professor_params)
    @professor.password = "1234"

    if @professor.save
      redirect_to admin_professors_path, notice: "#{@professor.name} was created successfully!"
    else
      render :index
    end
  end

  def edit
    @professor = Professor.find(params[:id])
  end

  def show
  end

  def update
    @professor = Professor.find(params[:id])
    if @professor.update_attributes(professor_params)
      redirect_to admin_professors_path
    else
      render :edit
    end
  end

  def destroy
    @professor = Professor.find(params[:id])
    @professor.destroy
    redirect_to admin_professors_path
  end

  def preferences
    @preferences = Professor.find(params[:professor_id]).preferences
  end

  def lectures
    @lectures = Professor.find(params[:professor_id]).lectures
  end

   private
  
  def professor_params
    params.require(:professor).permit(:name, :email, :kind, :status, :password, :password_confirmation)
  end
end

app/controllers/professors_controller.rb
class ProfessorsController < ApplicationController
  
  def new
    @professor = Professor.new
  end


  def create
    @professor = Professor.new(professor_params) 
    code1 = Ourconfig.find_by(name: "admin_code").value
    code2 = Ourconfig.find_by(name: "professor_code").value
    case professor_params[:kind].downcase
      when code1
        @professor.kind = 'admin' 
      when code2
        @professor.kind = 'professor'
      else
        @professor.kind = nil
    end
    if @professor.kind && @professor.save
    #this next if is for creating a super user that can edit the other professors kind
    #only this professor should use the admin code on the signup
      if @professor.kind == 'admin'
        new_config = Ourconfig.new
        new_config.name = "super_user_id"
        new_config.value = @professor.id 
        new_config.save       
      end
      session[:professor_id] = @professor.id
      redirect_to professor_path
    else
      render :new
    end
  end

  def show
    restrict_access
    @professor = current_professor
    redirect_to professor_preferences_path
  end

  def edit
    restrict_access
    @professor = current_professor
  end

  def update
    restrict_access
    @professor = current_professor
    if @professor.update_attributes(professor_params)
      redirect_to professor_path
    else
      render :edit
    end
  end

  def lectures
    @professor = current_professor
    @lectures = @professor.lectures    
  end

  def lectures_graph
    professor = current_professor
    lectures = professor.lectures    
    credit_of_semester = Hash.new(0)
    lectures.each do |lecture|
      credit_of_semester[lecture.semester] += lecture.course.credits
    end
    credit_of_semester = credit_of_semester.sort_by{|k,v|k}.to_h
    render json: credit_of_semester
  end

  protected
  def professor_params
    params.require(:professor).permit(:name, :email, :kind, :status, :password ,:password_confirmation)
    
  end
end

app/helpers/admin/professors_helper.rb
module Admin::ProfessorsHelper
end

app/helpers/professors_helper.rb
module ProfessorsHelper
end

app/views/admin/professors/create.html.erb
<h1>Admin::Professors#create</h1>
<p>Find me in app/views/admin/professors/create.html.erb</p>

app/views/admin/professors/destroy.html.erb
<h1>Admin::Professors#destroy</h1>
<p>Find me in app/views/admin/professors/destroy.html.erb</p>

app/views/admin/professors/edit.html.erb
<div class='well col-md-offset-3' style='width: 30%'>
  <%= form_for [:admin, @professor] do |f| %>
    <div class='form-group'>
        <%= f.label :name %><br>
        <%= f.text_field :name, placeholder:'name', class: 'form-control' %>
      </div>
      <div class='form-group'>
        <%= f.label :email %><br>
        <%= f.text_field :email, placeholder:'email', class: 'form-control' %>
      </div>
      <div class='form-group'>
        <%= f.label :password %><br>
        <%= f.password_field :password, placeholder: 'password', class: 'form-control' %>
      </div>
      <div class='form-group'>
        <%= f.label :password_confirmatioin %><br>
        <%= f.password_field :password_confirmatioin, placeholder: 'password', class: 'form-control' %>
      </div>
    <div class="form-group">
      <%= f.label "status" %><br>
      <%= f.select :status, options_for_select([["active","active"],["partial","partial"],["license","license"]],@professor.status)%>
    </div>
    <%if current_professor.id == Ourconfig.find_by(name: "super_user_id").value.to_i %>
      <div class="form-group">
        <%= f.label "kind" %><br>
        <%= f.select :kind, options_for_select([["professor","professor"],["admin","admin"]],@professor.kind)%>
      </div>
    <%end%>
    <div class='actions form-group'>
      <%= f.submit 'submit',class: 'btn btn-primary' %>
    </div>
  <% end %>

    <%= link_to 'Destroy', admin_professor_path(@professor), {method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-danger' ,style: "color:blue"} %>
</div>

app/views/admin/professors/index.html.erb
<h1>List of All Professors</h1>

<table class='table table-hover'>
  <thead>
    <tr>
      <th>Name</th>
      <th>Email</th>
      <th>Status</th>
    </tr>
  </thead>

  <tbody>
    <% @professors.sort_by{|professor| professor.name }.each do |professor| %>
      <tr>
        <td><%= link_to professor.name, edit_admin_professor_path(professor)  %></td>
        <td><%= professor.email %></td>
        <td><%= professor.status %></td>
        <td><%= link_to 'Preferences History', admin_professor_preferences_path(professor) %></td>
        <td><%= link_to 'Past Lecture History', admin_professor_lectures_path(professor) %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<div class="panel-default well">
  <div class="panel-heading">
    <h2 class="panel-title">Add a new Professor</h2>
  </div>
  <div class="panel-body">
    <%= form_for([:admin, @new_professor], html: {class:'form-inline'}) do |f| %>
      <div class="form-group">
        <%= f.label :name %>
        <%= f.text_field :name, class: 'form-control' %>
      </div>
      <div class="form-group">
        <%= f.label :email %>
        <%= f.text_field :email, class: 'form-control' %>
      </div>
      <div class="form-group">
        <%= f.label "status" %>
        <%= f.select :status, options_for_select([["active","active"],["partial","partial"],["license","license"]]), :prompt => "Please select" %>
      </div>
      <div class="actions form-group">
        <%= f.submit 'Add',:class => 'btn btn-info'  %>
      </div>
    <% end %>
  </div>
</div>

app/views/admin/professors/lectures.html.erb
<% if !@lectures.empty? %>
  <h2><%=@lectures.first.professor.name%> Lectures</h2>
  <%@lectures.each do |lecture|%>
    <div class="panel-primary well">
      <div class="panel-heading">
        <h4><%=decode_semester(lecture.semester)%></h4>
      </div>
      <div class="panel-body">
        <div><%=lecture.course.name%></div>
        <div><%=Offering.decode_schedule(lecture.schedule)%></div>
      </div>
    </div>
  <%end%>
<% else %>
  <h1>You have no lecture yet.</h1>
<% end %>

app/views/admin/professors/new.html.erb
<h1>Admin::Professors#new</h1>
<p>Find me in app/views/admin/professors/new.html.erb</p>

app/views/admin/professors/preferences.html.erb
<div class='container'>
  <% if !@preferences.empty? %>
    <h2 class='col-md-offset-4'><%=@preferences.first.professor.name%>'s Preferences</h2>
    <%@preferences.each do |preference|%>
      <div class="panel-info well">
        <div class="panel-heading">
          <h3 class='col-md-offset-5 panel-title'><%=decode_semester(preference.semester)%></h3>
        </div>
        <div class='panel-body'>
          <h5 class='col-md-6'>First preference for major</h5><h5 class='col-md-6'><strong><%= Offering.find(preference.first_major).course.name%></strong></h5>
          <h5 class='col-md-6'>Second preference for major</h5><h5 class='col-md-6'><strong><%=Offering.find(preference.second_major).course.name%></strong></h5>
          <h5 class='col-md-6'>Third preference for major</h5><h5 class='col-md-6'><strong><%=Offering.find(preference.third_major).course.name%></strong></h5>
          <h5 class='col-md-6'>First preference for service </h5><h5 class='col-md-6'><strong><%= Offering.find(preference.first_service).course.name%></strong></h5>
          <h5 class='col-md-6'>Second preference for service </h5><h5 class='col-md-6'><strong><%=Offering.find(preference.second_service).course.name%></strong></h5>
          <h5 class='col-md-6'>Third preference for service </h5><h5 class='col-md-6'><strong><%=Offering.find(preference.third_service).course.name%></strong></h5>
        </div>
      </div>
    <%end%>
  <% else %>
    <h2>You have no preference yet.</h2>
  <% end %>
</div>

app/views/admin/professors/show.html.erb
<h1>Admin::Professors#show</h1>
<p>Find me in app/views/admin/professors/show.html.erb</p>

app/views/admin/professors/update.html.erb
<h1>Admin::Professors#update</h1>
<p>Find me in app/views/admin/professors/update.html.erb</p>