config/routes.rb
Rails.application.routes.draw do

root to: 'sessions#new'
resource :professor, only: [:new, :create, :edit, :update, :show] do
  resources :preferences
  get '/lectures' => 'professors#lectures'
  get '/lectures_graph' => 'professors#lectures_graph'
end

resource :session, only: [:new, :create, :destroy]

namespace :admin do
  get '/offerings/score' => 'offerings#score'
  post '/offerings/random' => 'offerings#random'
  get '/offerings/domagic' => 'offerings#domagic'
  get '/offerings/domagicalltheway' => 'offerings#domagicalltheway'
  get '/offerings/clear' => 'offerings#clear_assignment'
  resources :professors do
    get '/preferences' => 'professors#preferences'
    get '/lectures' => 'professors#lectures'
  end
  resources :offerings do
    put '/resetprof' => 'offerings#resetprof'
  end
  resources :courses do
    get '/preferences' => 'courses#preferences'
    get '/lectures' => 'courses#lectures'
  end
  resource :preferences, only: [:index] do
    get '/professors' => 'preferences#professors'
    get '/offerings' => 'preferences#offerings'
  end
  get '/' => 'dashboard#index'
  post '/semester' => 'dashboard#semester'
  post '/notify_all' => 'dashboard#notify_all'

end

resources :lectures

end

app/views/layouts/_footer.html.erb
<footer class='footer'>
  <div class='container'>
  <h4>
    <% if current_professor %>
      <% if current_professor.kind == 'admin' %>
        Signed in as an Admin <%= current_professor.name %>(<%= link_to "back to admin dashboard", admin_path, method: :get %>)|(<%= link_to "Log out", session_path("current"), method: :delete %>)
      <% else %>
        Signed in as <%= current_professor.name %> (<%= link_to "Log out", session_path("current"), method: :delete %>)
      <% end %>
    <% else %>
      <%= link_to "Log In", new_session_path %> | <%= link_to "Sign Up", new_professor_path %>
    <% end %>
  </h4>
  </div>
</footer>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-default navbar-static-top">
  <div class="container">
    <div class="row">
      <div class="col-md-3 dropdown" style="margin-top: 2%">
        <% if current_professor %>
        <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Menu <span class="caret"></span></a>
        <ul class="dropdown-menu">
          <li><%= link_to 'My Preferences', professor_preferences_path, method: :get %></li>
          <li><%= link_to 'My Lectures', lectures_professor_path, method: :get %></li>
<!--           <li><a href="#">Something else here</a></li>
          <li role="separator" class="divider"></li>
          <li><a href="#">Separated link</a></li>
          <li role="separator" class="divider"></li>
          <li><a href="#">One more separated link</a></li> -->
        </ul>
        <% end %>
      </div>
      <div class="col-md-6">
        <% if current_professor && current_professor.kind == 'admin'%>
          <h4 id="top-name"><%= link_to 'EasySchedule',admin_path, method: :get %></h4>
        <% elsif current_professor %>
          <h4 id="top-name"><%= link_to 'EasySchedule',professor_preferences_path, method: :get %></h4>
        <% else %>
          <h4 id="top-name"><%= link_to 'EasySchedule',new_session_path, method: :get %></h4>
        <% end %>
      </div>
      <div class="col-md-3" style="margin-top: 2%">
        <ul class="nav">
          <% if current_professor %>
          <div class='col-md-10'>
            <li role="presentation" class="active">
              <h8><%= link_to current_professor.name, professor_preferences_path, method: :get %></h8>
            </li>
          </div>
          <div class='col-md-2'>
            <li>
              <h8><%= link_to "Logout", session_path("current"), method: :delete %></h8>
            </li>
          </div>
          <% else %>
          <div class='col-md-6'>
            <li role="presentation" class="active">
              <h8><%= link_to 'Login', new_session_path, method: :get %></h8>
            </li>
          </div>
          <div class='col-md-6'>
            <li>
              <h8><%= link_to "Signup", new_professor_path, method: :get %></h8>
            </li>
          </div>
          <% end %>
        </ul>
      </div>
    </div> 
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>EasySchedule</title>
  <%= stylesheet_link_tag    'application', media: 'all' %>
  <%= javascript_include_tag 'application'%>
  <script src='https://cdnjs.cloudflare.com/ajax/libs/Chart.js/1.0.2/Chart.min.js'></script>
  <%= csrf_meta_tags %>
</head>
<body>
    <%= render 'layouts/navbar' %>
    <div class='container' id="yieldcontent">
      <% flash.each do |key, value| %>
      <div class='alert alert-success'>
        <a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>
          <div><em> <%= value %></em></div>
      </div>
      <% end %>
      <%= yield %>
    </div>
    <%= render 'layouts/footer' %>
</body>
</html>